configVersion = 1

[window]
width = 1920
height = 1080
resizable = true
framerate = 60.0
uiScale = 1.0
vSync = true

[mods]
dataPackPath = "mods/data_packs"
resourcePackPath = "mods/resource_packs"
enabledDataPack = ["glimmerworks"]
enabledResourcePack = ["glimmerworks_res"]

[debug]
displayDebugPanel = false
displayBox2dShape = false
