startGame = "开始游戏"
settings = "设置"
mods = "模组"
exitGame = "退出游戏"
console = "终端"
commandNotFound = "命令未找到：{}"
executionFailed = "{}执行失败"
executedSuccess = "{}执行成功"
commandIsEmpty = "命令为空"
createWorld = "创建世界"
cancel = "取消"
confirm = "确认"
worldName = "世界名称"
seed = "种子"
random = "随机"
commandInfo = "共{}个命令已注册："
awakeBodyCount = "活跃的物理碰撞体数量：{}"
getActualPathError = "获取真实路径失败。"
unknownAssetType = "未知的资产类型。"
unknownCommandParameters = "未知的命令参数。"
worldContextIsNull = "尚未绑定到世界上下文。"
insufficientParameterLength = "参数长度不足，至少为{}，实际为{}。"
entryCannotFoundInConfigurationFile = "在配置文件内找不到条目{}。"
configurationUpdate = "配置{}已被更改为{}。"
itemIdNotFound = "物品Id没有找到。"
lootTableNotFound = "战利品表Id未找到。"
itemContainerIsNull = "物品容器是空的。"
composableItemIsNull = "可组合物品是空的。"
abilityItemIsNull = "Ability物品是空的。"
itemResourceNotFound = "没有找到itemResource。"
itemResourceIsNull = "itemResource是空的。"
tileResourceIsNull = "tileResource是空的。"
minXIsGreaterThanMaxX = "min X不能大于max X。"
folderCreationFailed = "文件夹{}创建失败。"
fileWritingFailed = "文件{}写入失败。"
failedToLoadLicense = "加载本地LICENSE文件失败。\n这个文件应该包含在这个程序的每个发行版中。\n如果缺少，请检查您的安装或在线查看许可证：\nhttps://github.com/Cold-Mint/GlimmerWorks/blob/master/LICENSE"
cantFindObject = "找不到游戏对象。"
teleportEntity = "已将Id为{}的实体，传送至x={},y={}。"
mapManifestIsNull = "mapManifest读取失败。"
savedGames = "保存的游戏"
loadGame = "加载游戏"
deleteGame = "删除存档"
wantDeleteThisSave = "您确定要删除此存档吗？"
savesList = "存档列表"
pause = "暂停"
restore = "恢复"
saveAndExit = "保存并退出"
worldNamePrefix = [ "安静", "神秘", "古老", "荒芜", "苍翠", "神圣", "幻想", "沉睡", "宁静", "寂静", "闪耀", "神奇", "荒野", "繁荣", "微光", "永恒", "迷雾", "迷人", "狂野", "奇幻", "温柔", "流光", "幽暗", "璀璨", "梦幻", "慵懒", "炽烈", "清冽", "缥缈", "深邃", "斑斓", "空灵", "温润", "浮空", "星坠", "月落", "风吟", "火舞", "冰凝", "软萌", "烬灭", "霜华", "雾隐", "星旋", "龙骸", "神域", "魔渊", "灵韵", "幻昼", "永夜", "陨星", "魂萦", "森罗", "万象", "穹顶", "深渊", "极光", "雷鸣", "潮汐", "尘嚣" ]
worldNameSuffix = [ "大陆", "海洋", "遗迹", "星辰", "秘境", "传说", "回响", "幻境", "花园", "森林", "河流", "山脉", "星空", "梦境", "天空", "深渊", "水晶", "陶瓷", "乐器", "峡谷", "溶洞", "冰川", "绿洲", "神域", "魔境", "潮汐", "晚风", "晨雾", "萤火", "风铃", "诗篇", "画卷", "歌谣", "琥珀", "琉璃", "玛瑙", "珊瑚", "灵域", "星轨", "月窟", "龙巢", "精灵谷", "薄荷", "幻海", "迷踪林", "永夜城", "陨星台", "魂冢", "云境", "雾屿", "灵墟", "圣坛", "魔殿", "星舰", "浮岛", "空岛", "灵泉", "幻镜", "神谕", "魔语", "古树", "秘泉", "符文阵", "传送门", "遗忘之地", "低语森林", "破碎穹顶" ]
