startGame = "開始遊戲"
settings = "設定"
mods = "模組"
exitGame = "退出遊戲"
console = "終端機"
commandNotFound = "命令未找到：{}"
executionFailed = "{}執行失敗"
executedSuccess = "{}執行成功"
commandIsEmpty = "命令為空"
createWorld = "創建世界"
cancel = "取消"
confirm = "確認"
worldName = "世界名稱"
seed = "種子"
random = "隨機"
commandInfo = "共{}個命令已註冊："
awakeBodyCount = "活躍的物理碰撞體數量：{}"
getActualPathError = "取得真實路徑失敗。"
unknownAssetType = "未知的資產類型。"
unknownCommandParameters = "未知的命令參數。"
worldContextIsNull = "尚未綁定到世界上下文。"
insufficientParameterLength = "參數長度不足，至少為{}，實際為{}。"
entryCannotFoundInConfigurationFile = "在設定檔內找不到項目{}。"
configurationUpdate = "設定{}已被更改為{}。"
itemIdNotFound = "物品ID未找到。"
lootTableNotFound = "戰利品表Id未找到。"
itemContainerIsNull = "物品容器為空。"
composableItemIsNull = "可組合物品為空。"
abilityItemIsNull = "Ability物品為空。"
itemResourceNotFound = "未找到itemResource。"
itemResourceIsNull = "itemResource為空。"
tileResourceIsNull = "tileResource為空。"
minXIsGreaterThanMaxX = "最小X座標不能大於最大X座標。"
folderCreationFailed = "資料夾{}創建失敗。"
fileWritingFailed = "檔案{}寫入失敗。"
failedToLoadLicense = "載入本地LICENSE檔案失敗。\n此檔案應包含在本程式的每個發行版本中。\n若遺失，請檢查您的安裝或線上查看授權條款：\nhttps://github.com/Cold-Mint/GlimmerWorks/blob/master/LICENSE"
cantFindObject = "找不到遊戲物件。"
teleportEntity = "已將ID為{}的實體，傳送至x={},y={}。"
mapManifestIsNull = "mapManifest讀取失敗。"
savedGames = "已儲存的遊戲"
loadGame = "載入遊戲"
deleteGame = "刪除存檔"
wantDeleteThisSave = "您確定要刪除此存檔嗎？"
savesList = "存檔列表"
pause = "暫停"
restore = "恢復"
saveAndExit = "儲存並退出"
screenshotSavedFailed = "截圖保存失敗{}。"
screenshotSavedSuccess = "截圖已保存至{}。"
worldNamePrefix = [ "安靜", "神祕", "古老", "荒蕪", "蒼翠", "神聖", "幻想", "沉睡", "寧靜", "寂靜", "閃耀", "神奇", "荒野", "繁榮", "微光", "永恆", "迷霧", "迷人", "狂野", "奇幻", "溫柔", "流光", "幽暗", "璀璨", "夢幻", "慵懶", "熾烈", "清冽", "縹緲", "深邃", "斑斕", "空靈", "溫潤", "浮空", "星墜", "月落", "風吟", "火舞", "冰凝", "軟萌", "燼滅", "霜華", "霧隱", "星旋", "龍骸", "神域", "魔淵", "靈韻", "幻晝", "永夜", "隕星", "魂縈", "森羅", "萬象", "穹頂", "深淵", "極光", "雷鳴", "潮汐", "塵囂" ]
worldNameSuffix = [ "大陸", "海洋", "遺跡", "星辰", "秘境", "傳說", "迴響", "幻境", "花園", "森林", "河流", "山脈", "星空", "夢境", "天空", "深淵", "水晶", "陶瓷", "樂器", "峽谷", "溶洞", "冰川", "綠洲", "神域", "魔境", "潮汐", "晚風", "晨霧", "螢火", "風鈴", "詩篇", "畫卷", "歌謠", "琥珀", "琉璃", "瑪瑙", "珊瑚", "靈域", "星軌", "月窟", "龍巢", "精靈谷", "薄荷", "幻海", "迷蹤林", "永夜城", "隕星台", "魂塚", "雲境", "霧嶼", "靈墟", "聖壇", "魔殿", "星艦", "浮島", "空島", "靈泉", "幻鏡", "神諭", "魔語", "古樹", "秘泉", "符文陣", "傳送門", "遺忘之地", "低語森林", "破碎穹頂" ]
